<?php
/**
 * n8nPress Internal Link Builder
 *
 * Scans post content for [INTERNAL_LINK: topic] markers generated by
 * the Content Scheduler and resolves them to actual <a> tags by matching
 * against products, categories, and posts.
 *
 * Can also be triggered via n8n for AI-powered link matching.
 *
 * @package n8nPress
 * @since 1.2.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class N8nPress_Internal_Linker {

	private static $instance = null;

	public static function get_instance() {
		if ( null === self::$instance ) {
			self::$instance = new self();
		}
		return self::$instance;
	}

	private function __construct() {
		add_action( 'rest_api_init', array( $this, 'register_endpoints' ) );

		// Daily cron to resolve unresolved markers
		add_action( 'n8npress_resolve_internal_links', array( $this, 'cron_resolve_links' ) );
		if ( ! wp_next_scheduled( 'n8npress_resolve_internal_links' ) ) {
			wp_schedule_event( time(), 'daily', 'n8npress_resolve_internal_links' );
		}

		// Fallback: resolve any remaining markers at render time
		add_filter( 'the_content', array( $this, 'filter_resolve_markers' ), 20 );
	}

	public function register_endpoints() {
		// Trigger link resolution for a specific post
		register_rest_route( 'n8npress/v1', '/content/resolve-links', array(
			'methods'             => 'POST',
			'callback'            => array( $this, 'handle_resolve_links' ),
			'permission_callback' => array( $this, 'check_permission' ),
			'args'                => array(
				'post_id' => array( 'required' => true, 'type' => 'integer', 'sanitize_callback' => 'absint' ),
			),
		) );

		// n8n callback: receive AI-matched links
		register_rest_route( 'n8npress/v1', '/content/resolve-links-callback', array(
			'methods'             => 'POST',
			'callback'            => array( $this, 'handle_resolve_callback' ),
			'permission_callback' => array( $this, 'check_n8n_token' ),
		) );

		// Scan all posts for unresolved markers
		register_rest_route( 'n8npress/v1', '/content/unresolved-links', array(
			'methods'             => 'GET',
			'callback'            => array( $this, 'handle_get_unresolved' ),
			'permission_callback' => array( $this, 'check_permission' ),
			'args'                => array(
				'limit' => array( 'default' => 50, 'sanitize_callback' => 'absint' ),
			),
		) );
	}

	// ─── REST: Resolve links for a single post ─────────────────────────

	public function handle_resolve_links( $request ) {
		$post_id = $request->get_param( 'post_id' );
		$post    = get_post( $post_id );

		if ( ! $post ) {
			return new WP_Error( 'not_found', 'Post not found.', array( 'status' => 404 ) );
		}

		$result = $this->resolve_markers_in_post( $post );

		return rest_ensure_response( $result );
	}

	// ─── REST: n8n callback with AI-matched links ──────────────────────

	public function handle_resolve_callback( $request ) {
		$data    = $request->get_json_params();
		$post_id = isset( $data['post_id'] ) ? absint( $data['post_id'] ) : 0;
		$links   = isset( $data['links'] ) ? (array) $data['links'] : array();

		if ( ! $post_id || ! get_post( $post_id ) ) {
			return new WP_Error( 'invalid_post', 'Valid post_id required.', array( 'status' => 400 ) );
		}

		if ( empty( $links ) ) {
			return new WP_Error( 'no_links', 'links array is required.', array( 'status' => 400 ) );
		}

		$post    = get_post( $post_id );
		$content = $post->post_content;
		$count   = 0;

		foreach ( $links as $link ) {
			$topic = sanitize_text_field( $link['topic'] ?? '' );
			$url   = esc_url( $link['url'] ?? '' );
			$anchor = sanitize_text_field( $link['anchor'] ?? $topic );

			if ( empty( $topic ) || empty( $url ) ) {
				continue;
			}

			$marker     = '[INTERNAL_LINK: ' . $topic . ']';
			$html_link  = '<a href="' . $url . '">' . esc_html( $anchor ) . '</a>';
			$new_content = str_replace( $marker, $html_link, $content );

			if ( $new_content !== $content ) {
				$content = $new_content;
				$count++;
			}
		}

		if ( $count > 0 ) {
			wp_update_post( array(
				'ID'           => $post_id,
				'post_content' => $content,
			) );
		}

		N8nPress_Logger::log( 'Internal links resolved via n8n callback', 'info', array(
			'post_id'  => $post_id,
			'resolved' => $count,
		) );

		return array(
			'success'  => true,
			'post_id'  => $post_id,
			'resolved' => $count,
		);
	}

	// ─── REST: Get posts with unresolved markers ───────────────────────

	public function handle_get_unresolved( $request ) {
		$limit = min( $request->get_param( 'limit' ), 200 );

		global $wpdb;
		$results = $wpdb->get_results( $wpdb->prepare(
			"SELECT ID, post_title, post_type
			 FROM {$wpdb->posts}
			 WHERE post_status = 'publish'
			   AND post_content LIKE %s
			 ORDER BY post_modified DESC
			 LIMIT %d",
			'%[INTERNAL_LINK:%',
			$limit
		) );

		$posts = array();
		foreach ( $results as $row ) {
			$content = get_post_field( 'post_content', $row->ID );
			preg_match_all( '/\[INTERNAL_LINK:\s*([^\]]+)\]/', $content, $matches );

			$posts[] = array(
				'post_id'   => (int) $row->ID,
				'title'     => $row->post_title,
				'post_type' => $row->post_type,
				'markers'   => $matches[1] ?? array(),
				'count'     => count( $matches[1] ?? array() ),
			);
		}

		return rest_ensure_response( array(
			'total' => count( $posts ),
			'posts' => $posts,
		) );
	}

	// ─── CRON: Daily resolve pass ──────────────────────────────────────

	public function cron_resolve_links() {
		if ( class_exists( 'N8nPress_Token_Tracker' ) && N8nPress_Token_Tracker::is_limit_exceeded() ) {
			N8nPress_Logger::log( 'Link resolver cron skipped: daily budget limit reached', 'warning' );
			return;
		}

		global $wpdb;
		$posts = $wpdb->get_results(
			"SELECT ID FROM {$wpdb->posts}
			 WHERE post_status = 'publish'
			   AND post_content LIKE '%[INTERNAL_LINK:%'
			 ORDER BY post_modified DESC
			 LIMIT 20"
		);

		$total_resolved = 0;
		foreach ( $posts as $row ) {
			$post   = get_post( $row->ID );
			$result = $this->resolve_markers_in_post( $post );
			$total_resolved += $result['resolved'];
		}

		if ( $total_resolved > 0 ) {
			N8nPress_Logger::log( 'Cron: internal links resolved', 'info', array(
				'posts_scanned' => count( $posts ),
				'links_resolved' => $total_resolved,
			) );
		}
	}

	// ─── FILTER: Runtime fallback resolution ───────────────────────────

	public function filter_resolve_markers( $content ) {
		if ( strpos( $content, '[INTERNAL_LINK:' ) === false ) {
			return $content;
		}

		return preg_replace_callback(
			'/\[INTERNAL_LINK:\s*([^\]]+)\]/',
			array( $this, 'resolve_single_marker' ),
			$content
		);
	}

	// ─── CORE: Resolve markers in a post ───────────────────────────────

	private function resolve_markers_in_post( $post ) {
		$content = $post->post_content;
		$count   = 0;

		preg_match_all( '/\[INTERNAL_LINK:\s*([^\]]+)\]/', $content, $matches, PREG_SET_ORDER );

		if ( empty( $matches ) ) {
			return array(
				'post_id'  => $post->ID,
				'resolved' => 0,
				'remaining' => 0,
			);
		}

		foreach ( $matches as $match ) {
			$full_marker = $match[0];
			$topic       = trim( $match[1] );
			$link        = $this->find_best_match( $topic );

			if ( $link ) {
				$html    = '<a href="' . esc_url( $link['url'] ) . '">' . esc_html( $link['anchor'] ) . '</a>';
				$content = str_replace( $full_marker, $html, $content );
				$count++;
			}
		}

		if ( $count > 0 ) {
			wp_update_post( array(
				'ID'           => $post->ID,
				'post_content' => $content,
			) );
		}

		// Count remaining unresolved
		preg_match_all( '/\[INTERNAL_LINK:\s*([^\]]+)\]/', $content, $remaining );

		return array(
			'post_id'   => $post->ID,
			'resolved'  => $count,
			'remaining' => count( $remaining[0] ),
		);
	}

	/**
	 * Resolve a single marker (for the_content filter)
	 */
	private function resolve_single_marker( $match ) {
		$topic = trim( $match[1] );
		$link  = $this->find_best_match( $topic );

		if ( $link ) {
			return '<a href="' . esc_url( $link['url'] ) . '">' . esc_html( $link['anchor'] ) . '</a>';
		}

		// Can't resolve — return topic text without marker
		return esc_html( $topic );
	}

	// ─── MATCHING: Find best product/category/post for a topic ─────────

	private function find_best_match( $topic ) {
		$topic_lower = mb_strtolower( $topic );

		// 1. Exact title match in products
		$match = $this->search_posts( $topic, 'product' );
		if ( $match ) {
			return $match;
		}

		// 2. Product category match
		$match = $this->search_terms( $topic, 'product_cat' );
		if ( $match ) {
			return $match;
		}

		// 3. Blog post title match
		$match = $this->search_posts( $topic, 'post' );
		if ( $match ) {
			return $match;
		}

		// 4. Page match
		$match = $this->search_posts( $topic, 'page' );
		if ( $match ) {
			return $match;
		}

		// 5. Product tag match
		$match = $this->search_terms( $topic, 'product_tag' );
		if ( $match ) {
			return $match;
		}

		return null;
	}

	private function search_posts( $topic, $post_type ) {
		global $wpdb;

		// Try exact match first
		$post = $wpdb->get_row( $wpdb->prepare(
			"SELECT ID, post_title FROM {$wpdb->posts}
			 WHERE post_type = %s AND post_status = 'publish'
			   AND post_title = %s
			 LIMIT 1",
			$post_type,
			$topic
		) );

		// Fallback to LIKE match
		if ( ! $post ) {
			$post = $wpdb->get_row( $wpdb->prepare(
				"SELECT ID, post_title FROM {$wpdb->posts}
				 WHERE post_type = %s AND post_status = 'publish'
				   AND post_title LIKE %s
				 ORDER BY LENGTH(post_title) ASC
				 LIMIT 1",
				$post_type,
				'%' . $wpdb->esc_like( $topic ) . '%'
			) );
		}

		if ( $post ) {
			return array(
				'url'    => get_permalink( $post->ID ),
				'anchor' => $post->post_title,
				'type'   => $post_type,
				'id'     => (int) $post->ID,
			);
		}

		return null;
	}

	private function search_terms( $topic, $taxonomy ) {
		$term = get_term_by( 'name', $topic, $taxonomy );

		if ( ! $term ) {
			// Fuzzy search
			global $wpdb;
			$term = $wpdb->get_row( $wpdb->prepare(
				"SELECT t.term_id, t.name FROM {$wpdb->terms} t
				 INNER JOIN {$wpdb->term_taxonomy} tt ON t.term_id = tt.term_id
				 WHERE tt.taxonomy = %s AND t.name LIKE %s
				 ORDER BY LENGTH(t.name) ASC
				 LIMIT 1",
				$taxonomy,
				'%' . $wpdb->esc_like( $topic ) . '%'
			) );

			if ( $term ) {
				$term = get_term( $term->term_id, $taxonomy );
			}
		}

		if ( $term && ! is_wp_error( $term ) ) {
			return array(
				'url'    => get_term_link( $term ),
				'anchor' => $term->name,
				'type'   => $taxonomy,
				'id'     => $term->term_id,
			);
		}

		return null;
	}

	// ─── PERMISSIONS ───────────────────────────────────────────────────

	public function check_permission( $request ) {
		return N8nPress_Permission::check_token_or_admin( $request );
	}

	public function check_n8n_token( $request ) {
		return N8nPress_Permission::check_token( $request );
	}
}
